### ISSUE TITLE
Certain (bad) link goes to bluehost 404 page not my custom 404 page

### ISSUE THREAD

**Issue by shareyourrepair** [kunalnagar/custom-404-pro#10]
I was going through the 404 errors in my Google Webmaster Tools and discovered a bad link that was pulling my my web host's 404 page not my custom 404 page like all my other bad links show.   The url of the page that was showing the bluehost 404 page is: http://www.shareyourrepair.com/search/label/A/C 

I contacted bluehost and they tinkered around with my site and renamed the bluehost 404 page and then that link above started redirecting to my homepage instead, which still isn't what should happen.  Anyway, I just wanted to see what you thought about this issue.  Thanks again for your plugin, it has been VERY useful to me.

John

**Comment by kunalnagar** [comment]
John,

Glad to hear that the plugin is working out for you :+1: 

So as long as you are visiting any URL that is within the WordPress site, the plugin should be able to redirect it to the page you've mentioned in the Plugin Settings. Otherwise, any other URL would throw a 404 error on the Bluehost page. I hope that helps.

Marking as resolved for now.

-Kunal

**Comment by shareyourrepair** [comment]
What is qualified as "within the WordPress site"?  The path must be within the WordPress site?

**Comment by kunalnagar** [comment]
The URL that you are visiting should be part of the WordPress site.

For example, you might be hosting a non-WordPress site at www.abc.com but you might be hosting a WordPress blog at www.abc.com/blog

If you get a 404 on www.abc.com/blog/anythinghere, this falls under the WordPress install. But if you get a 404 on www.abc.com/blah, this would take you to the Bluehost 404 page.

Hope that helps!
