### ISSUE TITLE
Clearing logs

### ISSUE THREAD

**Issue by jnptechnical** [kunalnagar/custom-404-pro#20]
Hi there,
I can't seem to be able to clear some of the logs (now turned logging off) - where are these located in the db so i could remove them please?

Regards,
Jack

**Comment by kunalnagar** [comment]
@jnptechnical Clearing logs is something that's not 100% bug-free. The internal logic deletes logs incrementally. This will be fixed in the next release. In the meantime, I recommend clicking on the "Clear Logs" button and then waiting for a minute or two and then checking if part of the logs have cleared or not.

**Comment by kunalnagar** [comment]
@jnptechnical Just Released v.2.0.0 of the plugin that has better feedback for clearing logs. Update and try :)

**Comment by jnptechnical** [comment]
Awesome, thank you.

I'll give that a go!

**Comment by kunalnagar** [comment]
@jnptechnical I just released a bugfix in 2.0.1. Could you update and let me know if it's working?

**Comment by jnptechnical** [comment]
Hey buddy,
All seems to be working perfectly, very impressed, the counter is a nice touch!

**Comment by kunalnagar** [comment]
@jnptechnical That's great, thanks!
