### ISSUE TITLE
Redirect not working

### ISSUE THREAD

**Issue by Aidan-Goldman** [kunalnagar/custom-404-pro#42]
Hi Kunal,

When I enter a URL that does not exist on my site, it is not redirecting to the specified 404 page, and therefore any changes I make to my 404 page are not updating. Please let me know if I have not defined my 404 redirect correctly.

Thanks,
Aidan

**Comment by kunalnagar** [comment]
@Aidan-Goldman to be clear:

1. You're visiting page X on your website that should result in a 404
2. You have specified a page Y in the Custom 404 Pro settings using the "Page" option
3. When you visit X, it's not redirecting to Y

Is that correct? If yes, can you try a couple of options:

1. Can you switch to the "Custom URL" option and see if that works for you?
2. Can you delete the plugin, re-install it and try again?
3. Also, what version of WordPress and plugin are you running?

Let me know what works!

**Comment by Aidan-Goldman** [comment]
Hi Kunal,


Thank you for the prompt response! That is a correct assessment of the issue.

We are using WordPress version 4.9.6

It works the same whether I switch the Mode is set to WordPress Page or to URL

I will try uninstalling and reinstalling on Monday and let you know how it goes. Have a good weekend.


Best,

Aidan Goldman
Technical Support Engineer
Business Forecast Systems, Inc.
617 484 5050
agoldman@forecastpro.com<mailto:agoldman@forecastpro.com>
www.forecastpro.com<http://www.forecastpro.com/>

**Comment by kunalnagar** [comment]
@Aidan-Goldman just checking in to see if you had time to test out the clean install of the plugin?

**Comment by Aidan-Goldman** [comment]
Hi Kunal,


I have just tested this and it appears to have worked. Note, I had to set it to URL mode instead of specifying it by the WordPress Page name.

Thank you very much for reaching out and making sure this is working as expected. I appreciate it greatly.


Best,

Aidan Goldman
Technical Support Engineer
Business Forecast Systems, Inc.
617 484 5050
agoldman@forecastpro.com<mailto:agoldman@forecastpro.com>
www.forecastpro.com<http://www.forecastpro.com/>

**Comment by kunalnagar** [comment]
@Aidan-Goldman it should work with the page option as well. 

The first step in debugging any WordPress plugin is to deactivate other plugins on your website one by one and see if this fixes the issue. Maybe you're using a theme or plugin that hooks into the [is_404()](https://codex.wordpress.org/Function_Reference/is_404) method and that might conflict with this plugin.

Just in case you're curious, feel free to try the above step on a staging environment or something and you'll have better knowledge of what is actually going on.

Otherwise, URL mode works well too. The only issue would be if the ```slug``` of the page changed, you would have to manually go and update it in the plugin.

Again, thanks for using the plugin :) If possible, please take a minute to rate it on the WordPress plugin repository: https://wordpress.org/plugins/custom-404-pro/
